apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: traefik
  name: traefik-ingress-controller

---
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  namespace: traefik
  name: traefik
  labels:
    app: traefik

spec:
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        # - name: traefik
        #   image: traefik:v2.0
        #   args:
        #     - --api
        #     - --accesslog
        #     - --ping
        #     - --entrypoints.http.Address=:80
        #     - --providers.kubernetescrd
        #   ports:
        #     # - name: http
        #     #   containerPort: 80
        #     - name: admin
        #       containerPort: 8080
        - name: nginx
          image: nginx
          ports:
            - name: http
              containerPort: 80
