apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      nodePort: 30035
    - protocol: TCP
      name: admin
      port: 8080
      nodePort: 30036
    # - protocol: TCP
    #   name: whoami
    #   port: 80
    #   nodePort: 30037
  selector:
    app: traefik