- name: Load certificates
  unarchive:
    src: "{{ playbook_dir }}/pki/worker-pki.tgz"
    dest: /home/ec2-user

- name: Generate configuration generator scripts
  template:
    src: "templates/{{item}}.kubeconfig-generator.sh"
    dest: "{{item}}.kubeconfig-generator.sh"
  with_items:
    - kube-proxy
    - kubelet

- name: Execute configuration generator scripts
  shell: "bash {{item}}.kubeconfig-generator.sh"
  with_items:
    - kube-proxy
    - kubelet