- name: Reset kubeadm
  command: kubeadm reset --force
  become: yes
  tags: 
    - reset

- name: Render kubeadm-config
  template:
    src: templates/kubeadm-config.j2
    dest: kubeadm-config.yaml
  when: inventory_hostname == groups["masters"][0]
  tags:
    - init
  
- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --config=kubeadm-config.yaml --upload-certs
  when: inventory_hostname == groups["masters"][0]
  register: kubeadm_init_output
  args:
    creates: /etc/kubernetes/admin.conf
  become: yes
  tags:
    - init

- name: Copy kubeadm controller join command
  local_action: command "echo {{ kubeadm_init_output.stdout }} | sed -n '65,68p' -  > {{ role_path }}/scripts//controller-join-command.sh"
  when: inventory_hostname == groups["masters"][0] 
  tags:
    - init

- name: Copy kubeadm worker join command
  local_action: copy content="{{ kubeadm_init_output.stdout_lines[75:76] }}" dest="{{ role_path }}/scripts/worker-join-command.sh"
  when: inventory_hostname == groups["masters"][0] 
  tags:
    - init

- name: Allow ec2-user to use kubectl
  script: scripts/kubectl-config.sh
  when: inventory_hostname == groups["masters"][0]

- name: Install calico pod network
  become: false
  command: kubectl create -f https://docs.projectcalico.org/v3.8/getting-started/kubernetes/installation/hosted/calico.yaml
  when: inventory_hostname == groups["masters"][0]

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command
  when: inventory_hostname == groups["masters"][0] 

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="{{ role_path }}/scripts/join-command.sh"
  when: inventory_hostname == groups["masters"][0] 

- name: Other controllers join cluster
  script: "{{ role_path }}/scripts/join-command.sh"
  when: inventory_hostname != groups["masters"][0]
  become: yes