---
# - hosts: ca
#   roles:
#     - ca

- hosts: masters
  roles:
    # - etcd
    - kube-controller

# - hosts: workers
#   roles:
#     - kube-worker

# - hosts: masters
#   roles:
#     - master

# - hosts: workers
#   roles:
#     - worker